
name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  EnvVariable-Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create variable in PowerShell
        shell: pwsh
        run: | 
          $TestVariable = "This is a test"
          Write-Host $TestVariable
          echo "NEW_VARIABLE=$TestVariable" >> $GITHUB_ENV
        
      - name: Call variable in PowerShell
        shell: pwsh
        run: |
          echo ${{ env.NEW_VARIABLE }}
          Write-Host ${{ env.NEW_VARIABLE }}
          
      - name: Set the value
        id: step_one
        run: |
          echo "action_state=yellow" >> $GITHUB_ENV
      - name: Use the value
        id: step_two
        run: |
          echo "${{ env.action_state }}" # This will output 'yellow'
