
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Create variable in PowerShell
        shell: pwsh
        run: | 
          $TestVariable = "This is a test"
          Write-Host $TestVariable
        
      - name: Call variable in PowerShell
        shell: pwsh
        run: Write-Host $TestVariable
