name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


  workflow_dispatch:

jobs:
  GitHubEnv-Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create variable in PowerShell
        shell: pwsh
        run: |
          echo "Test"
          $TestVariable = "This is a test"
          echo "NEW_VARIABLE=${{$TestVariable}}" >> $GITHUB_ENV
        
      - name: Call variable in PowerShell
        shell: pwsh
        run: Write-Host $NEW_VARIABLE
     
